AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wish-log-analysis-api

  SAM Template for wish-log-analysis-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30  # Increased timeout for LLM operations
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  AnalyzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: wish_log_analysis_api.app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Environment:
        Variables:
          LANGCHAIN_TRACING_V2: false
          LANGCHAIN_ENDPOINT: ""
          LANGCHAIN_API_KEY: ""
          OPENAI_API_KEY: ""
      Events:
        Analyze:
          Type: Api
          Properties:
            Path: /analyze
            Method: post

Outputs:
  AnalyzeApi:
    Description: API Gateway endpoint URL for Prod stage for Analyze function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/"
  AnalyzeFunction:
    Description: Analyze Lambda Function ARN
    Value: !GetAtt AnalyzeFunction.Arn
  AnalyzeFunctionIamRole:
    Description: Implicit IAM Role created for Analyze function
    Value: !GetAtt AnalyzeFunctionRole.Arn
