AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wish-log-analysis-api

  SAM Template for wish-log-analysis-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30  # Increased timeout for LLM operations
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: false
    OpenApiVersion: '2.0'
    EndpointConfiguration: REGIONAL

Resources:
  WishLogAnalysisApiDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: wish-log-analysis-api-dep-layer
      ContentUri: ./vendor/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  AnalyzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src.wish_log_analysis_api.app.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          WISH_HOME: ''
          WISH_API_BASE_URL: ''
          OPENAI_API_KEY: ''
          OPENAI_MODEL: ''
          OPENAI_EMBEDDING_MODEL: ''
          LANGCHAIN_TRACING_V2: ''
          LANGCHAIN_ENDPOINT: ''
          LANGCHAIN_API_KEY: ''
          LANGCHAIN_PROJECT: ''
      Events:
        Analyze:
          Type: Api
          Properties:
            Path: /analyze
            Method: post
      Layers:
        - !Ref WishLogAnalysisApiDepLayer

Outputs:
  AnalyzeApi:
    Description: API Gateway endpoint URL for Prod stage for Analyze function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyze/"
  AnalyzeFunction:
    Description: Analyze Lambda Function ARN
    Value: !GetAtt AnalyzeFunction.Arn
  AnalyzeFunctionIamRole:
    Description: Implicit IAM Role created for Analyze function
    Value: !GetAtt AnalyzeFunctionRole.Arn
