AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  RapidPen Cloud - Log Analysis API Component (wish-log-analysis-api)

Parameters:
  Environment:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prd
    Description: Deployment environment

  OpenAIApiKey:
    Type: String
    NoEcho: true

  OpenAIModel:
    Type: String
    Default: gpt-4o

  ApiBaseUrl:
    Type: String

  LangchainApiKey:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: false
    OpenApiVersion: '2.0'
    EndpointConfiguration: EDGE
    Auth:
      ApiKeyRequired: true

Resources:
  # API Gateway
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration: EDGE
      TracingEnabled: false
      OpenApiVersion: '2.0'
      Auth:
        ApiKeyRequired: true

  # API Key and Usage Plan
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "rapidpen-cloud-key-${Environment}"
      Description: !Sub "API key for RapidPen Cloud ${Environment}"
      Enabled: true
  
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "rapidpen-cloud-usage-plan-${Environment}"
      Description: !Sub "Usage plan for RapidPen Cloud ${Environment}"
      ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref Environment
      Throttle:
        BurstLimit: 10
        RateLimit: 5
  
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  RapidPenCloudDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "rapidpen-cloud-dep-layer-${Environment}"
      ContentUri: ./vendor/
      CompatibleRuntimes:
        - python3.13
      RetentionPolicy: Retain

  AnalyzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "rapidpen-cloud-analyze-${Environment}"
      CodeUri: ./
      Handler: src.wish_log_analysis_api.app.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          WISH_HOME: ''
          WISH_API_BASE_URL: !Ref ApiBaseUrl
          OPENAI_API_KEY: !Ref OpenAIApiKey
          OPENAI_MODEL: !Ref OpenAIModel
          OPENAI_EMBEDDING_MODEL: 'text-embedding-3-small'
          LANGCHAIN_TRACING_V2: 'true'
          LANGCHAIN_ENDPOINT: 'https://api.smith.langchain.com'
          LANGCHAIN_API_KEY: !Ref LangchainApiKey
          LANGCHAIN_PROJECT: !Sub "rapidpen-cloud-${Environment}"
      Events:
        Analyze:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /analyze
            Method: post
      Layers:
        - !Ref RapidPenCloudDepLayer
      Tags:
        Environment: !Ref Environment
        Service: wish-log-analysis-api
        Project: RapidPen-Cloud

Outputs:
  AnalyzeApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/analyze/"
  AnalyzeFunction:
    Description: Analyze Lambda Function ARN
    Value: !GetAtt AnalyzeFunction.Arn
  AnalyzeFunctionIamRole:
    Description: Implicit IAM Role created for Analyze function
    Value: !GetAtt AnalyzeFunctionRole.Arn
  ApiId:
    Description: API Gateway ID
    Value: !Ref ApiGatewayApi
  ApiKey:
    Description: API Key ID
    Value: !Ref ApiKey
