# Pre-commit hooks for wish-tools
repos:
  - repo: local
    hooks:
      - id: generate-tool-docs
        name: Generate tool documentation
        entry: uv run python scripts/generate_tool_docs.py
        language: system
        files: ^src/wish_tools/tools/.*\.py$
        pass_filenames: false
        always_run: false
        
      - id: run-tool-tests
        name: Run tool tests
        entry: uv run python scripts/test_tools.py
        language: system
        files: ^src/wish_tools/.*\.py$
        pass_filenames: false
        always_run: false