name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  component-tests:
    name: Component Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: uv sync --all-packages --dev
      
      - name: Run component integration tests
        run: uv run pytest e2e-tests/component/ -v
        env:
          PYTEST_TIMEOUT: 300

  workflow-tests:
    name: Workflow Integration Tests
    runs-on: ubuntu-latest
    needs: component-tests
    steps:
      - uses: actions/checkout@v3
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: uv sync --all-packages --dev
      
      - name: Run workflow tests
        run: uv run pytest e2e-tests/workflows/ -v
        env:
          PYTEST_TIMEOUT: 600

  scenario-tests:
    name: Scenario Tests (Mock)
    runs-on: ubuntu-latest
    needs: workflow-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: uv sync --all-packages --dev
      
      - name: Run scenario tests (mock only)
        run: uv run pytest e2e-tests/scenarios/ -k "mock" -v
        env:
          PYTEST_TIMEOUT: 900

  quality-tests:
    name: AI Quality Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: uv sync --all-packages --dev
      
      - name: Run AI quality tests
        run: uv run pytest e2e-tests/quality/ -v
        env:
          PYTEST_TIMEOUT: 300

  summary:
    name: E2E Test Summary
    runs-on: ubuntu-latest
    needs: [component-tests, workflow-tests, quality-tests]
    if: always()
    steps:
      - name: Check test results
        run: |
          if [[ "${{ needs.component-tests.result }}" != "success" ]] || \
             [[ "${{ needs.workflow-tests.result }}" != "success" ]] || \
             [[ "${{ needs.quality-tests.result }}" != "success" ]]; then
            echo "❌ E2E tests failed"
            exit 1
          else
            echo "✅ All E2E tests passed"
          fi