name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g. 0.1.0)'
        required: true
        type: string

jobs:
  publish:
    name: Publish wish packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - wish-sh
          - wish-command-execution
          - wish-models

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.package }}/.python-version"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Update version in pyproject.toml
      - name: Update version in pyproject.toml
        run: |
          sed -i "s/version = \"[^\"]*\"/version = \"${{ inputs.version }}\"/" ${{ matrix.package }}/pyproject.toml
          echo "Updated version in ${{ matrix.package }}/pyproject.toml to ${{ inputs.version }}"
          grep -m 1 'version = ' ${{ matrix.package }}/pyproject.toml

      - name: Build package
        run: cd ${{ matrix.package }} ; python -m build

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: cd ${{ matrix.package }} ; twine upload dist/*
