name: "Wish: Python Lint & Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - wish-sh
          - wish-knowledge-loader
          - wish-command-execution
          - wish-command-generation
          - wish-command-generation-api
          - wish-log-analysis
          - wish-log-analysis-api
          - wish-models
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.project }}/.python-version"

      - name: Install the project
        run: cd ${{ matrix.project }} ; uv sync --all-extras --dev

      - name: Run lint
        run: cd ${{ matrix.project }} ; uv run ruff check

  test:
    name: Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - wish-sh
          - wish-knowledge-loader
          - wish-command-execution
          - wish-command-generation
          - wish-command-generation-api
          - wish-log-analysis
          - wish-log-analysis-api
          - wish-models
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.project }}/.python-version"

      - name: Install the project
        run: cd ${{ matrix.project }} ; uv sync --all-extras --dev

      - name: Setup environment variables for testing
        run: |
          # Check if .env.example exists
          if [ ! -f .env.example ]; then
            echo "Error: .env.example file not found"
            exit 1
          fi
          
          # Setup environment variables
          mkdir -p ~/.wish/
          cp .env.example ~/.wish/env
          
          # Set API keys from GitHub Secrets
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> ~/.wish/env
          echo "LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY }}" >> ~/.wish/env

      - name: Run tests
        run: cd ${{ matrix.project }} ; uv run pytest
