name: "Wish: Python Lint & Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - wish-sh
          - wish-command-execution
          - wish-command-generation
          - wish-models
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.project }}/.python-version"

      - name: Install the project
        run: cd ${{ matrix.project }} ; uv sync --all-extras --dev

      - name: Run lint
        run: cd ${{ matrix.project }} ; uv run ruff check

  test:
    name: Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - wish-sh
          - wish-command-execution
          - wish-command-generation
          - wish-models
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "${{ matrix.project }}/.python-version"

      - name: Install the project
        run: cd ${{ matrix.project }} ; uv sync --all-extras --dev

      - name: Setup environment variables for testing
        run: cd ${{ matrix.project }} && [ -f .env.example ] && cp .env.example .env || echo "No .env.example file found"

      - name: Run tests
        run: cd ${{ matrix.project }} ; uv run pytest
